### ISSUE TITLE
sql.Scan does not work for mssql driver

### ISSUE THREAD

**Issue by mantzas** [satori/go.uuid#19]
Hi,

i am having a problem when scanning from MS SQL Server a uuid.
The uuid from the app and the value in the db table is the same, but when querying and scan the result i get a different uuid. The same app does work in PostgreSQL just by switching out the driver.
Any thoughts?

**Comment by satori** [comment]
What mssql driver do you use?

**Comment by mantzas** [comment]
- https://github.com/denisenkom/go-mssqldb

- checkout Read function in https://github.com/mantzas/incata/blob/master/sql_reader.go
 
- PostgreSQL has the uuid type and MS Sql Server has the UNIQUEIDENTIFIER type

- Expected 7bcdad57-4ff7-45d7-9c1f-16b452ce230e but was 57adcd7b-f74f-d745-9c1f-16b452ce230e

**Comment by satori** [comment]
Though Microsoft GUID and UUID are both 128-bits value, the problem is that [GUID is not UUID][1]. While [RFC 4122][2] defines UUID as 16 bytes in big-endian format (also known as network byte order), GUID is defined as:
```cpp
typedef struct _GUID {
  DWORD Data1;
  WORD  Data2;
  WORD  Data3;
  BYTE  Data4[8];
} GUID
```
That literally means that first 64 bits of GUID are in native platform format (I assume you are using x86, which means little-endian) and last 64 bits are in big-endian format.

This library assumes that byte slice passed to `UnmarshalBinary()` is in RFC big-endian format.

In the same time GUID and UUID have the same text representation, so casting your GUID field into string should help:
```sql
CAST(Id AS char(36))
```

Unfortunately I don't have an access to MS SQL server and can't test it.

[1]: https://en.wikipedia.org/wiki/Globally_unique_identifier#Binary_encoding
[2]: https://tools.ietf.org/html/rfc4122#section-4.1.2

**Comment by mantzas** [comment]
You are right. I did the cast in the select statement and all is well. Funny thing. When inserting it works automatically. The SQL Profiler revealed that the insert statement had the UUID converted into `N'30bc04c2-d35b-4373-8d4e-9dbe653ff714'`! So the above cast worked! Thanks very much!

**Comment by satori** [comment]
That works, because UUID is [marshalled into string][1] as a part of `driver.Valuer` interface implementation. AFAIK `lib/pq` currently doesn't support Postgres' binary protocol and uses ASCII representation for query results. That's why UUID [could be scanned either from string or byte slice][2].

[1]: https://github.com/satori/go.uuid/blob/master/uuid.go#L278-L281
[2]: https://github.com/satori/go.uuid/blob/master/uuid.go#L283-L299

**Comment by mantzas** [comment]
Got it. Thanks again.
